#!/bin/bash

# Stop the script on any error
set -e

# Variables
KEY_NAME="btp_app_key"
PUB_KEY="/home/arcus/.ssh/${KEY_NAME}.pub"
PRIVATE_KEY="/home/arcus/.ssh/${KEY_NAME}"

# Check if the .pem key already exists locally
# Note: the .pem is generated by Terraform via the tls_private_key resource.
# If it already exists, Terraform will skip regenerating it.
if [ -f "$PRIVATE_KEY" ]; then
    echo "key already exists: $PRIVATE_KEY"
else
    echo "SSH key not found, terraform wil generate it" 
fi

# Initialize Terraform and apply the configuration to create the EC2 instance
echo "Initializing and applying Terraform..."
cd ./terraform
terraform init  # Initialize Terraform and download providers

terraform plan 
# terraform apply tfplan
terraform apply -auto-approve  # Apply Terraform configuration without manual approval

# At this point Terraform has:
# - Generated a RSA private key
# - Saved it as ~/.ssh/btp_app_key.pem (permissions 0400)
# - Registered the matching public key on AWS
# - Created the EC2 instance and Elastic IP

# Retrieve the public IP address of the EC2 instance
echo "Retrieving the public IP address of the EC2 instance..."
INSTANCE_IP=$(terraform output -raw elastic_ip)


echo "Instance IP: ${INSTANCE_IP}"

# Create a dynamic Ansible inventory file
echo "Creating the Ansible inventory..."
cat > ../ansible/inventory.ini <<EOF
[awsservers]
$INSTANCE_IP ansible_user=ubuntu
EOF


# Indicate that the deployment is complete
echo "Deployment completed successfully!"
echo "Connect to your instance with:"
echo "  ssh -i $PRIVATE_KEY -p 2222 ubuntu@${INSTANCE_IP}"



# Wait for the instance to be ready (SSH may not be available immediately)
# sleep 60

# Run the Ansible playbook to install Docker
# echo "Running the Ansible playbook..."
# ansible-playbook -i ../inventory.ini ansible_playbook.yml \
#   --private-key "$PUB_KEY" \
#   --ssh-extra-args='-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'
