#!/bin/bash

# Stop the script on any error
set -e

# Variables
KEY_NAME="btp_app_key"
PEM_FILE="/home/arcus/.ssh/${KEY_NAME}.pem"

# Check if the .pem key already exists locally
# Note: the .pem is generated by Terraform via the tls_private_key resource.
# If it already exists, Terraform will skip regenerating it.
if [ -f "$PEM_FILE" ]; then
    echo "PEM key already exists: $PEM_FILE"
else
    echo "PEM key not found — Terraform will generate it automatically."
fi

# Initialize Terraform and apply the configuration to create the EC2 instance
echo "Initializing and applying Terraform..."
terraform init  # Initialize Terraform and download providers
terraform apply -auto-approve  # Apply Terraform configuration without manual approval

# At this point Terraform has:
# - Generated a RSA private key
# - Saved it as ~/.ssh/btp_app_key.pem (permissions 0400)
# - Registered the matching public key on AWS
# - Created the EC2 instance and Elastic IP

# Retrieve the public IP address of the EC2 instance
echo "Retrieving the public IP address of the EC2 instance..."
INSTANCE_IP=$(terraform output -raw elastic_ip)
echo "Instance IP: ${INSTANCE_IP}"

# Create a dynamic Ansible inventory file
echo "Creating the Ansible inventory..."
cat > ../inventory.ini <<EOF
[awsservers]
$INSTANCE_IP ansible_user=ubuntu
EOF

echo "Inventory written to ../inventory.ini"

# Wait for the instance to be ready (SSH may not be available immediately)
# sleep 60

# Run the Ansible playbook to install Docker
# echo "Running the Ansible playbook..."
# ansible-playbook -i ../inventory.ini ansible_playbook.yml \
#   --private-key "$PEM_FILE" \
#   --ssh-extra-args='-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'

# Indicate that the deployment is complete
echo ""
echo "Deployment completed successfully!"
echo "Connect to your instance with:"
echo "  ssh -i $PEM_FILE ubuntu@${INSTANCE_IP}"